### ISSUE TITLE
Issue in Netbeans

### ISSUE THREAD

**Issue by wsalex** [kmrifat/StoreKeeper#1]
Hi i'm using netbeans 8.0.2  and i have two errors in output windows.
Please check imae attached:
C:\Users\Usuario\Desktop\StoreKeeper-master\nbproject\jfx-impl.xml:1135: The following error occurred while executing this line:
C:\Users\Usuario\Desktop\StoreKeeper-master\nbproject\jfx-impl.xml:1212: Warning: Could not find resource file "C:\Users\Usuario\Desktop\StoreKeeper-master\${libs.MySQLDriver.classpath}" to copy.
BUILD FAILED (total time: 0 seconds)
![captura](https://cloud.githubusercontent.com/assets/17167381/13056929/ba27f4c8-d3e6-11e5-80a4-7c57a994fdb1.JPG)

**Comment by wsalex** [comment]
One more question. What license is this app?

**Comment by kmrifat** [comment]
Did you try to rebuild MySQL Driver path??
Maybe netbeans can't find the MySQL Driver path, that's why she threw an error.

This project under "GNU General Public License version 2.0 (GPLv2)".

**Comment by wsalex** [comment]
Ok thank you, it just work but i can't access because there is not username and password?

**Comment by kmrifat** [comment]
You can't access.. where?? 
if you can't access to MySQL Database for the password issue then please check out DBConnection.class in dataBase package. and edit username , password or the database name. 
![image](https://cloud.githubusercontent.com/assets/6764959/13104702/e832f4e6-d588-11e5-846a-434e623771be.png)
if u do not use any password for mysql then keep password variable as blank.
